      SUBROUTINE RUN(NSTOKES, NUMMU, AZIORDER, MU_VALUES,
     .                    SRC_CODE, LAYER_FILE, OUT_FILE,
     .                    QUAD_TYPE, DELTAM, DIRECT_FLUX, DIRECT_MU,
     .                    GROUND_TEMP, GROUND_TYPE,
     .                    GROUND_ALBEDO, GROUND_INDEX,
     .                    SKY_TEMP, WAVELENGTH, UNITS, OUTPOL,
     .                    NOUTLEVELS, OUTLEVELS, NUMAZIMUTHS, MAXLAY,
     .                    HEIGHT, TEMPERATURES, GAS_EXTINCT, SCAT_FILES)
      INTEGER   NSTOKES, NUMMU, AZIORDER
      INTEGER   NUM_LAYERS, SRC_CODE
      CHARACTER*64 LAYER_FILE, OUT_FILE
      CHARACTER QUAD_TYPE*1, DELTAM*1, UNITS*1, OUTPOL*2, GROUND_TYPE*1
      INTEGER   NOUTLEVELS, OUTLEVELS(NOUTLEVELS), NUMAZIMUTHS
      REAL*8    GROUND_TEMP, GROUND_ALBEDO
      COMPLEX*16  GROUND_INDEX
      REAL*8    SKY_TEMP, WAVELENGTH
C      REAL*8    MAX_DELTA_TAU
      REAL*8    DIRECT_FLUX, DIRECT_MU
      REAL*8    MU_VALUES(NUMMU)
      
CF2PY INTENT(OUT) HEIGHT, TEMPERATURES,GAS_EXTINCT, SCAT_FILES
      REAL*8    HEIGHT(MAXLAY), TEMPERATURES(MAXLAY)
      REAL*8    GAS_EXTINCT(MAXLAY)
      CHARACTER*64 SCAT_FILES(MAXLAY)
      INTEGER MAXA
      PARAMETER(MAXA=32)
      
      
      
      IF (1+AZIORDER .GT. MAXA) THEN
          WRITE (*,*) 'Maximum number of azimuth modes exceeded.'
          STOP
      ENDIF


      CALL READ_LAYERS (LAYER_FILE, MAXLAY, NUM_LAYERS,
     .                  HEIGHT, TEMPERATURES,
     .                  GAS_EXTINCT, SCAT_FILES)
     
      
      END