      SUBROUTINE RUN(LAYF, OUTF, MIDX, R0, R1, GAMMA, NPTS, WL, TAUA, 
     .               TAUM, NMOMS, QUAD_TYPE, DELTAM, GROUND_ALBEDO)
      

CF2PY INTENT(IN)  LAYF, OUTF, MIDX, R0, R1, GAMMA, NPTS, WL, TAUA
CF2PY INTENT(IN)  TAUM, NMOMS, QUAD_TYPE, DELTAM, GROUND_ALBEDO

      CHARACTER*64  LAYF, OUTF
      COMPLEX*16    MIDX, GROUND_INDEX
      REAL*8        R0, R1, GAMMA, WL, TAUA, TAUM
      INTEGER       NPTS, NMOMS

      EXTERNAL RT3, MKLYFL

      INTEGER NSTOKES, NUMMU, AZIORDER, SRC_CODE, NUMAZIMUTHS
      PARAMETER(NUMMU=32)   
      REAL*8  MU_VALUES(2*NUMMU), DIRECT_FLUX, DIRECT_MU, GROUND_TEMP,
     .        GROUND_ALBEDO, SKY_TEMP
      
      CHARACTER QUAD_TYPE*1, DELTAM*1, UNITS*1, OUTPOL*2, GROUND_TYPE*1

      


      CALL MKLYFL(LAYF, MIDX, R0, R1, GAMMA, NPTS, WL, TAUA, TAUM, 
     .            NMOMS)

      
      NSTOKES = 2
      AZIORDER = 6
      SRC_CODE = 1
      GROUND_TYPE = 'L'
      GROUND_INDEX = (1.0, 0.0)
      UNITS = 'W'
      OUTPOL = 'IQ'
      NUMAZIMUTHS = 2

      CALL RT3(NSTOKES, NUMMU, AZIORDER, MU_VALUES,
     .                    SRC_CODE, LAYF, OUTF,
     .                    QUAD_TYPE, DELTAM, DIRECT_FLUX, DIRECT_MU,
     .                    GROUND_TEMP, GROUND_TYPE,
     .                    GROUND_ALBEDO, GROUND_INDEX,
     .                    SKY_TEMP, WL, UNITS, OUTPOL,
     .                    NUMAZIMUTHS)


      END