      SUBROUTINE RUNRT3(LAYF, OUTF, WL, DIRECT_FLUX, DIRECT_MU, 
     .               QUAD_TYPE, DELTAM, GROUND_ALBEDO, NUMMU, 
     .               MU, IV, QV)

      IMPLICIT NONE


CF2PY INTENT(IN)  LAYF, OUTF, WL
CF2PY INTENT(IN)  DIRECT_FLUX, DIRECT_MU, NUMMU
CF2PY INTENT(IN)  QUAD_TYPE, DELTAM, GROUND_ALBEDO
CF2PY INTENT(OUT) MU, IV, QV

      CHARACTER*64  LAYF, OUTF
      COMPLEX*16    GROUND_INDEX

      EXTERNAL RT3, POSTPROCESS
      INTEGER NSTOKES, NUMMU, AZIORDER, SRC_CODE, NUMAZIMUTHS
      REAL*8  MU_VALUES(2*NUMMU), DIRECT_FLUX, DIRECT_MU, GROUND_TEMP,
     .        GROUND_ALBEDO, SKY_TEMP, MU(2*NUMMU), IV(2*NUMMU), 
     .        QV(2*NUMMU), WL
      
      CHARACTER QUAD_TYPE*1, DELTAM*1, UNITS*1, OUTPOL*2, GROUND_TYPE*1

      NSTOKES = 2
      AZIORDER = 6
      SRC_CODE = 1
      GROUND_TYPE = 'L'
      GROUND_INDEX = (1.0, 0.0)
      UNITS = 'W'
      OUTPOL = 'IQ'
      NUMAZIMUTHS = 2

      CALL RT3(NSTOKES, NUMMU, AZIORDER, MU_VALUES,
     .                    SRC_CODE, LAYF, OUTF,
     .                    QUAD_TYPE, DELTAM, DIRECT_FLUX, DIRECT_MU,
     .                    GROUND_TEMP, GROUND_TYPE,
     .                    GROUND_ALBEDO, GROUND_INDEX,
     .                    SKY_TEMP, WL, UNITS, OUTPOL,
     .                    NUMAZIMUTHS)


      CALL POSTPROCESS(OUTF, NUMMU, MU, IV, QV)

      END


      